words = [
    "ack",
    "acks",
    "broadcasted",
    "cuda",
    "dbus",
    "distil",
    "enigo",
    "fft",
    "keepalive",
    "menjivar",
    "mistralai",
    "openai",
    "safetensors",
    "stt",
    "sttd",
    "tekken",
    "udp",
    "vergen",
    "voxtral",
]
